# Generated by Django 3.1.7 on 2021-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceluploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='state',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='city',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='district',
            field=models.CharField(default=True, max_length=2501),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='phone',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
